refactor: Removed main function for better app flow

diff --git a/prod/tests/test-main-image b/prod/tests/test-main-image
--- a/prod/tests/test-main-image
+++ b/prod/tests/test-main-image
@@ -66,7 +66,7 @@ function test_no_leaked_tool_from_stage_builder() {
 }
 
 test_broken_pip_packages() {
-    docker run --rm --entrypoint pip "${PROD_IMAGE}" check > /dev/null
+    docker run --rm --entrypoint pip "${PROD_IMAGE}" check >/dev/null
     result=$?
     if [ "${result}" -ne 0 ]; then
         echo "ERROR: A Python requirement is broken. Exit code ${result}" >&2
@@ -97,20 +97,16 @@ test_entrypoint() {
     fi
 }
 
-function main() {
-    if [[ -z "${PROD_IMAGE}" ]]; then
-        echo "ERROR: PROD_IMAGE is not defined." && exit 1
-    fi
-    test_non_root_user
-    test_non_root_group
-    test_user_name
-    test_group_name
-    test_user_ownership
-    test_group_ownership
-    test_no_leaked_tool_from_stage_builder
-    test_broken_pip_packages
-    test_os_dependencies_are_installed
-    test_entrypoint
-}
-
-main
+if [[ -z "${PROD_IMAGE}" ]]; then
+    echo "ERROR: PROD_IMAGE is not defined." && exit 1
+fi
+test_non_root_user
+test_non_root_group
+test_user_name
+test_group_name
+test_user_ownership
+test_group_ownership
+test_no_leaked_tool_from_stage_builder
+test_broken_pip_packages
+test_os_dependencies_are_installed
+test_entrypoint
