feat: Made scripts alpine ready.

diff --git a/prod/tests/test-main-image b/prod/tests/test-main-image
--- a/prod/tests/test-main-image
+++ b/prod/tests/test-main-image
@@ -1,12 +1,12 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
-set -euo pipefail
+set -euo
 
 user="tasky"
 group="tasky"
 healtcheck_url="http://localhost:8000/healthz/"
 
-function test_non_root_user() {
+test_non_root_user() {
 	result=$(docker run --rm --entrypoint id "${PROD_IMAGE}" -u)
 	if [ "${result}" -eq 0 ]; then
 		echo "ERROR: UID is ${result}. This is the root user." && exit 1
@@ -14,7 +14,7 @@ function test_non_root_user() {
 	echo "PASSED: User is not root user."
 }
 
-function test_non_root_group() {
+test_non_root_group() {
 	result=$(docker run --rm --entrypoint id "${PROD_IMAGE}" -g)
 	if [ "${result}" -eq 0 ]; then
 		echo "ERROR: GID is ${result}. This is the root group." && exit 1
@@ -22,7 +22,7 @@ function test_non_root_group() {
 	echo "PASSED: Group is not root group."
 }
 
-function test_user_name() {
+test_user_name() {
 	result=$(docker run --rm --entrypoint id "${PROD_IMAGE}" -un)
 	if [ "${result}" != "${user}" ]; then
 		echo "ERROR: User is ${result}. This is not user '${user}'." && exit 1
@@ -30,7 +30,7 @@ function test_user_name() {
 	echo "PASSED: User is '${user}'."
 }
 
-function test_group_name() {
+test_group_name() {
 	result=$(docker run --rm --entrypoint id "${PROD_IMAGE}" -gn)
 	if [ "${result}" != "${group}" ]; then
 		echo "ERROR: Group is ${result}. This is not group '${group}'." && exit 1
@@ -38,7 +38,7 @@ function test_group_name() {
 	echo "PASSED: Group is '${group}'."
 }
 
-function test_user_ownership() {
+test_user_ownership() {
 	result=$(docker run --rm --entrypoint sh "${PROD_IMAGE}" -c 'stat -c "%U" .')
 	if [ "${result}" != "${user}" ]; then
 		echo "ERROR: User '${user}' is not the ower of the working directory." && exit 1
@@ -46,7 +46,7 @@ function test_user_ownership() {
 	echo "PASSED: User '${user}' has ownership."
 }
 
-function test_group_ownership() {
+test_group_ownership() {
 	result=$(docker run --rm --entrypoint sh "${PROD_IMAGE}" -c 'stat -c "%G" .')
 	if [ "${result}" != "${group}" ]; then
 		echo "ERROR: Group '${group}' is not the ower of the working directory." && exit 1
@@ -54,9 +54,8 @@ function test_group_ownership() {
 	echo "PASSED: Group '${group}' has ownership."
 }
 
-function test_no_leaked_tool_from_stage_builder() {
-	deps=("poetry" "gcc" 'make')
-	for dep in "${deps[@]}"; do
+test_no_leaked_tool_from_stage_builder() {
+	for dep in poetry gcc make; do
 		docker run --rm --entrypoint sh "${PROD_IMAGE}" -c 'command -v ${tool}'
 		result=$?
 		if [ "${result}" -eq 127 ]; then
@@ -70,15 +69,13 @@ test_broken_pip_packages() {
 	docker run --rm --entrypoint pip "${PROD_IMAGE}" check >/dev/null
 	result=$?
 	if [ "${result}" -ne 0 ]; then
-		echo "ERROR: A Python requirement is broken. Exit code ${result}" >&2
-		exit 1
+		echo "ERROR: A Python requirement is broken. Exit code ${result}" >&2 && exit 1
 	fi
 	echo "PASSED: No broken requirements found."
 }
 
-function test_os_dependencies_are_installed() {
-	deps=("curl" "nc")
-	for dep in "${deps[@]}"; do
+test_os_dependencies_are_installed() {
+	for dep in curl nc; do
 		docker run --rm --entrypoint sh "${PROD_IMAGE}" -c 'command -v ${dep} > /dev/null'
 		result=$?
 		if [ "${result}" -ne 0 ]; then
@@ -98,15 +95,16 @@ test_entrypoint() {
 	fi
 }
 
-function test_healthcheck_configured() {
+test_healthcheck_configured() {
 	result=$(docker inspect --format '{{json .Config.Healthcheck}}' "${PROD_IMAGE}")
-	if ! [[ "${result}" == *"curl -fsS ${healtcheck_url}"* ]]; then
-		echo "ERROR: HEALTHCHECK command not found." && exit 1
-	fi
-	echo "PASSED: image has a HEALTHCHECK hitting ."
+	case "${result}" in
+	*"curl -fsS ${healtcheck_url}"*) ;;
+	*) echo "ERROR: HEALTHCHECK command not found." >&2 && exit 1 ;;
+	esac
+	echo "PASSED: image has a HEALTHCHECK hitting ${healtcheck_url}."
 }
 
-if [[ -z "${PROD_IMAGE}" ]]; then
+if [ -z "${PROD_IMAGE}" ]; then
 	echo "ERROR: PROD_IMAGE is not defined." && exit 1
 fi
 test_non_root_user
