feat: Adapted script to new runner and backend

diff --git a/infrastructure/scripts/gitlab-runner b/infrastructure/scripts/gitlab-runner
--- a/infrastructure/scripts/gitlab-runner
+++ b/infrastructure/scripts/gitlab-runner
@@ -10,8 +10,14 @@ Usage:
 Commands:
   help          Shows this help message
   install       Install gitlab-runner
+  update        Update gitlab-runner
   destroy       Destroy gitlab-runner
 EOF
+}
+
+function set_script_dir() {
+	SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+	cd "$SCRIPT_DIR/../terraform/environment/dev/gitlab-runner" || exit 2
 }
 
 function install() {
@@ -24,30 +30,19 @@ function install() {
 		help && exit 1
 	fi
 
-	SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-	cd "$SCRIPT_DIR/../terraform/environment/dev/gitlab-runner" || exit 2
+	set_script_dir
 
 	read -rp "Runner name: " runner_name
 	export TF_VAR_runner_name=${runner_name}
 
 	read -rp "Runner token: " runner_token
 
+	read -rp "Availability zone: " availability_zone
+	export TF_VAR_availability_zone=${availability_zone}
+
 	terraform init -reconfigure \
 		-backend-config="bucket=tasky-tf-state-${TF_VAR_owner_id}-dev" \
-		-backend-config="key=runner/dev/${runner_name}/terraform.tfstate"
-
-	if aws s3api head-bucket --bucket "ansible-ssm-${TF_VAR_owner_id}-dev" &>/dev/null; then
-		echo "INFO: Importing already existing objects."
-
-		terraform import module.ssm_transfer_bucket.aws_s3_bucket.this "ansible-ssm-${TF_VAR_owner_id}-dev" || true
-		terraform import aws_s3_bucket_policy.ssm_bucket "ansible-ssm-${TF_VAR_owner_id}-dev" || true
-		terraform import aws_s3_bucket_lifecycle_configuration.ssm_bucket "ansible-ssm-${TF_VAR_owner_id}-dev" || true
-		terraform import module.security.aws_iam_role.runner "runner-role-dev-${runner_name}" || true
-		terraform import module.security.aws_iam_instance_profile.runner "runner-profile-dev-${runner_name}" || true
-		terraform import module.security.aws_iam_role_policy.ssm_bucket_access "runner-role-dev-${runner_name}:ssm-bucket-access" || true
-		terraform import "module.security.aws_iam_role_policy_attachment.runner[\"arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore\"]" \
-			"runner-role-dev-${runner_name}/arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore" || true
-	fi
+		-backend-config="key=runner/${availability_zone}/${runner_name}/terraform.tfstate"
 
 	terraform apply -var-file=../default.tfvars -var-file=terraform.tfvars || exit 3
 
@@ -59,7 +54,44 @@ function install() {
 		-i inventory/aws_ec2.yaml \
 		-l "runner_dev_${runner_name}" \
 		-e runner_name="${runner_name}" \
+		-e availability_zone="${availability_zone}" \
 		-e runner_token="${runner_token}" \
+		-e owner_id="${TF_VAR_owner_id}"
+}
+
+function update() {
+	if [[ -z "${TF_VAR_owner_id}" || -z "${AWS_PROFILE}" ]]; then
+		if [[ -z "${TF_VAR_owner_id}" ]]; then
+			echo "ERROR: TF_VAR_owner_id is not set"
+		else
+			echo "ERROR: AWS_PROFILE is not set"
+		fi
+		help && exit 1
+	fi
+
+	set_script_dir
+
+	read -rp "Runner name: " runner_name
+	export TF_VAR_runner_name=${runner_name}
+
+	read -rp "Availability zone: " availability_zone
+	export TF_VAR_availability_zone=${availability_zone}
+
+	terraform init -reconfigure \
+		-backend-config="bucket=tasky-tf-state-${TF_VAR_owner_id}-dev" \
+		-backend-config="key=runner/${availability_zone}/${runner_name}/terraform.tfstate"
+
+	terraform apply -var-file=../default.tfvars -var-file=terraform.tfvars || exit 3
+
+	cd "$SCRIPT_DIR/../ansible/environment/dev/gitlab-runner" || exit 4
+
+	ansible-galaxy collection install -r requirements.yaml -p ./collections
+
+	ANSIBLE_CONFIG=./ansible.cfg ansible-playbook playbook.yaml \
+		-i inventory/aws_ec2.yaml \
+		-l "runner_dev_${runner_name}" \
+		-e runner_name="${runner_name}" \
+		-e availability_zone="${availability_zone}" \
 		-e owner_id="${TF_VAR_owner_id}"
 }
 
@@ -72,19 +104,18 @@ function destroy() {
 		fi
 		help && exit 1
 	fi
-	SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-	cd "$SCRIPT_DIR/../terraform/environment/dev/gitlab-runner" || exit 2
+
+	set_script_dir
 
 	read -rp "Runner name: " runner_name
 	export TF_VAR_runner_name=${runner_name}
 
-	terraform init -reconfigure \
-		-backend-config="bucket=tasky-terraform-state-${TF_VAR_owner_id}-dev" \
-		-backend-config="key=runner/dev/${runner_name}/terraform.tfstate"
+	read -rp "Availability zone: " availability_zone
+	export TF_VAR_availability_zone=${availability_zone}
 
-	terraform state rm module.ssm_transfer_bucket || true
-	terraform state rm aws_s3_bucket_policy.ssm_bucket || true
-	terraform state rm aws_s3_bucket_lifecycle_configuration.ssm_bucket || true
+	terraform init -reconfigure \
+		-backend-config="bucket=tasky-tf-state-${TF_VAR_owner_id}-dev" \
+		-backend-config="key=runner/${availability_zone}/${runner_name}/terraform.tfstate"
 
 	terraform destroy --auto-approve \
 		-var-file=../default.tfvars -var-file=terraform.tfvars ||
@@ -95,6 +126,8 @@ if [[ "$1" == "help" ]]; then
 	help
 elif [[ "$1" == "install" ]]; then
 	install
+elif [[ "$1" == "update" ]]; then
+	update
 elif [[ "$1" == "destroy" ]]; then
 	destroy
 else
